language: node_js
node_js:
  - "stable"
sudo: required
services:
  - docker
cache:
  directories:
  - node_modules
script:
  - yarn install
  - yarn test
  - yarn build
deploy:
  provider: script
  script: yarn publishTest
  on:
    branch: travis