language: node_js
node_js:
- stable
sudo: required
services:
- docker
script:
- docker-compose build
- docker tag lightapp2-broker-prod rooknj/lightapp2:broker-$tag
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push rooknj/lightapp2:broker-$tag
  on:
    branch: master
env:
  global:
  - tag: latest
  - secure: GBDSRD9OrjSd7QhhqtP5xIJlrL5YAXJKaJ0SBkh9zM3IyKNmzEH0AKQ3R51dpNkwPh57nPUhcHIZXvDtTNdwKBqeqLa+BUHIHNlls2Cs3YK+z8WcyM1korzM0l4Y50vN20THz/+vY2Dk8sq3f/5GuL0k8EpXgsjeLamimvVM87F/H9pMyR4AbelkaqOVFPFCtgzA3Jx47v56mXpm2B42Cq+ttYg/ClC0+ya8zVVBZHYlvKvZ9tVlqcAMClufKyZfoTBHA3ZWsyhhiB3CINVkJ+WqJFCEFkHmab+PK89EBClCPZ2Ezado1+4ip9NNUi/SXwSV1vtl/T2JX+f9aTSm3vXpAsYBVg+9LKUolZLUAS4RlMVaAxglVbMtPRQU3oinGa9+mTXtFSQ2QRei81diksLYCoHY5VviO5zGsOiw71zAoNPqFrFSXIrgGt3yGlxefMfMG4/NcwaUqJmmHhbEqx8Sy35dmGZHeHCwoFcGqvHliWDK43QpUYzY6RbdpVcgKIhmNM8DPUo7PQI6Uv6Ta6sPgpVl45pPrX51kexUOo+DoQyPBpzQBD3K3vv97J8zsDqAMyIJCjtqJmgVNknDgNtmBS7QtQsjqyc/69H78wLBIK+fgb/WL3kHon+i/Tb6Ae3tV0hrGjMYNDl5H4w/4Em1rRnuxH4l7ZJOcMxsxHg=
