language: node_js
node_js:
- stable
sudo: required
services:
- docker
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
- docker run --rm --privileged multiarch/qemu-user-static:register --reset #This adds QEMU to the travis instance which allows us to run commands on the ARM architecture within docker images
- docker-compose build
- docker tag lightapp2-server-prod rooknj/lightapp2:server-$tag
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push rooknj/lightapp2:server-$tag
  on:
    branch: master
env:
  global:
    secure: OG30DUqQgP0+UwBnC2eF/iOGlrTllqDiIbYJRqxGS2Dq4daSBv7NX3mv5NkeVis4qa0DnfnvTM/h1p4WTqD1Vd0WWQx+/EPcV9i3SzZwLnN5OsV+Tnl0o8Y8/E7kCQ5p3P/5EApRDa7ffTOYhjs2tEk37qsQo3hNm3cqySQK+l1qmDqpyATd5SRVFExyw0LzasaPH52YcbZwGuASKH8BPysy3FUt8WpSTzLNaWVrJH+GkWjLYfQjrLXd7pA2BZW93P8hG2xJN5vCEdnnPYvzsmOk7ksBG2CX+7jIUaE3KsXjSPqnwC0ntspvE/gDx/lQ4gyas74gVZn9BcBqq76Zd+z56kvDXUWl+lKeNhDzz3JqZi6/6Kcm+bSNECC0zJOUie8H/R/U2jj7IDJSurPXLUFK5ortQa7AW+NErDkzFkcCY4dBByl9RYgp0pMBCbUP/qo3bu+osMrRLxie0tQ3aXCMZ8H5n9usx1xaGH9e0oTiFIjYT3ykrkBZ55EP39D1MA7rMYAevQLdmEpTNhENnfr7DPCXftObDdvCFxuzZrR6qDPLczQq91hsTfsnSyXUdQOw6FhT98kdZFhmOs5OybhyEk6Aq0U29pKdiY3/nYCDEKmk7LypdaOfTq6B7i5MFn7FHfhViTUSED+Ng1ydwuF4rgh3/49GB1ZB/J8UZe8=
    tag: latest