language: node_js
node_js:
- stable
sudo: required
services:
- docker
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install --silent
script:
- node scripts/dockerScripts build
- yarn testIntegration
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  skip_cleanup: true
  script: node scripts/dockerScripts tag && node scripts/dockerScripts publish
  on:
    all_branches: true
env:
  global:
  - secure: njje9sb+thffhIo3evEYJM2wowYK/dt+1kCe2oACGVJ3m1bHxAoM6qi2RLlMubfP0fmelZgHSbjxLVZc/bjvnAQ0Vk5QdWHDGGxJmYnTiHDwrJMhBjDxoW7GGJDyb5Cc4UtcKJ8gAIWmVn4GmkRLj+ktNZO1Gzd1qtYLEQVwvUG/eppIRKHcicAHSqsahkmjIcvgQIGmQd1AMDfod3N7Nx1Hy5oQLQTop5vFZEGV1kBZ6WRtn3N5q6t17z1753ZNxjgS3xnqO+H9QLuMvb7YuDg8aO+f53+iK62lYUK77D5lluH2v96ZSPuvJkPEu04zz2SxW3gvaRzRyUNl0K5881chR9TLQGlJVJdRvJmngxnMeHSzaqoV2ZtXf/SULZtMrxVidzHeEuOVdfC5EO8e3XUQNeTAYQT4SwHxFK1DOIdLjjHJvnEjkqhDbreDzMxHdF9AHK9hC3t/bb0I//33RffV+t0Izf4xK3GFpLgM0bodu6r9XZkI59FlbSz20YHZgXI2F5E53TefHlo1vnIHr6iIOqBoNc+T5lQ/zw++gQ2sahIc+R3dcIleu7X6ZbbsXbyet9flSpDnWUOIFlZfbD3AJC3SbJCACjWQag9frFcj0CLZV+iIGn6aTd9kVDN/h0bXsE987khfK/IbLZ7eyv9ypM564VYLwW2fMqtmYS4=
notifications:
  slack:
    secure: CfeajzhOWlkHvyGNASBrFji4E4Q6xiArJm7rvBldR33VxLmaW38H3+UXXo59+A84vRiFtUxb3Z+4DQiWlORgbRFyKBUMAavX17V9HjcAWSPD91V+uzrTIdeZuvHv02yLuqs9gY7nB+tAxGBgPagE3Ah5Oz/fLC0KNM3fd99JLOYl+dPk3+t6zhWD74OM1T7bbxXz7RzEk09pb8dAdUm9xFyCybU8TQcain9vR5m8YRCjCutv9MzXC5AUDB6vnh1y7KxCW42xcZgFw4wow2BrtKRTsMk0m/BpzLS2YvmVIVDk7FNPsO93bZudlYpDRIzaYShqoQZOe1o0Ol42j4EyxiKP8Lo2d/UMwO0DxXRSZ7waj/HjgooDayu3NjWcnNW9L8kv4TsLFHs4pErwCVjnMHFrDhCmhidwVtPav0EBAwOlK24EKUyqzc3alu4E8SJqKnlQZX+ahTybyRKUPkSY1YVJCmSYjafrhWjAdEEWEL5zWZxUZgOC87DXb3sIjfcCeHQGMpPJSL8OBGq9sd3IVGbkM7coo01RtttGOu9n1egt4EEMZgYGEHxjFojQiE31yuk1kEpk/KLfLlm8zFHLfgGakGmeQt3zYTaV4dOSN84LHpsCC4pJZpmtf5YGl5Sayw8kADZTZcd/10ElatBkstfp6JAkMDI8t7HCfEcl8yU=
