language: node_js
node_js:
- stable
sudo: required
services:
- docker
script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker-compose -f docker-compose.rpi.yml build
- docker tag lightapp2-broker-rpi rooknj/lightapp2:broker-rpi-$tag
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push rooknj/lightapp2:broker-x64-$tag && docker push rooknj/lightapp2:broker-rpi-$tag
  on:
    branch: master
env:
  global:
  - tag: latest
  - secure: GBDSRD9OrjSd7QhhqtP5xIJlrL5YAXJKaJ0SBkh9zM3IyKNmzEH0AKQ3R51dpNkwPh57nPUhcHIZXvDtTNdwKBqeqLa+BUHIHNlls2Cs3YK+z8WcyM1korzM0l4Y50vN20THz/+vY2Dk8sq3f/5GuL0k8EpXgsjeLamimvVM87F/H9pMyR4AbelkaqOVFPFCtgzA3Jx47v56mXpm2B42Cq+ttYg/ClC0+ya8zVVBZHYlvKvZ9tVlqcAMClufKyZfoTBHA3ZWsyhhiB3CINVkJ+WqJFCEFkHmab+PK89EBClCPZ2Ezado1+4ip9NNUi/SXwSV1vtl/T2JX+f9aTSm3vXpAsYBVg+9LKUolZLUAS4RlMVaAxglVbMtPRQU3oinGa9+mTXtFSQ2QRei81diksLYCoHY5VviO5zGsOiw71zAoNPqFrFSXIrgGt3yGlxefMfMG4/NcwaUqJmmHhbEqx8Sy35dmGZHeHCwoFcGqvHliWDK43QpUYzY6RbdpVcgKIhmNM8DPUo7PQI6Uv6Ta6sPgpVl45pPrX51kexUOo+DoQyPBpzQBD3K3vv97J8zsDqAMyIJCjtqJmgVNknDgNtmBS7QtQsjqyc/69H78wLBIK+fgb/WL3kHon+i/Tb6Ae3tV0hrGjMYNDl5H4w/4Em1rRnuxH4l7ZJOcMxsxHg=
notifications:
  slack:
    secure: TeHXuSo+aRpYDcE1LI2Ic4c5/JWO2LFtB0/Kvur9e5K9XKasnvjZiC08DmassXyAEeiYY1xcKj+Hci9vzSt7dfbDqlBPlpdBYt/qSkV1WYSKKMzAgbgKGFvlCdcuGJofw97/crYyoapjcy8lVszD4Wq51J5X2NU/9rdL3ZgwSGzn6FqxxGqbGNsBMwVT3WaH+5ddAkc0ijHOXBdS8ZZA3JPS2TjD4bFcxcs9IuAbeKiT6Nxqdo/hjVQcf2cAPii5gDgG9FLvgiEjfIWF2LZDzEklTSiHLRPMc+POqJG7OHpMuf8/rZEza7blHfwl26vFuieY9Y0lTV3wpzm/f3oqG0OUUkKERPA+of+GHMDrNcRlefXdL71eEB8tioRRcqrKjKILTA4d4dQrelkrngnLKb3xJPuZqYYQVzJa48lmmezQ+CuIn9/gXjVXXYYho2+/w6TbCGplqRXbov6mjCqPSe5Sano86eo5yp8iMpHCBsbxS9HVtWeICd/0QmLd4TqrUuA81rgBymIEiEbYKJqpxMmwR5+SncyMiTVACuEHeBqMQEbTJtV6PnTNk+wanoCY7EQwy1boZRNgAnQoSm3UxM3MVtJWMwHiyBMBVL8uwLWrK0QboytK0tTcQS1S22imazf8a7Pb7DYEiN1JOAI/NwHjsdTXfTRKQboCiGq8aVA=
