language: node_js
node_js: 10
sudo: required
services:
- docker
cache: npm
before_install:
  - npm i minimist cross-spawn
script: node scripts/dockerUtil.js build
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  skip_cleanup: true
  script: node scripts/dockerUtil.js publish
  on:
    all_branches: true
env:
  global:
    secure: YkvWxe2j5MrBJ08yruMuNlA5oJXIaKS5zJec4Su6Vd7c9UAGIh0HDiZx6q1EARjhtE783l2d2TCYxjPbdg5TxKHzzXtTZNqIvj8uRDFz2ODAHCXsJiseiEiv2bGvjAKwj3Por5UaBMfZ7rLwdLeLfI+tRBIo4IklKNX7+OsW8L4XZK+b9Mbmo/RW6P4O877chuz6wlma1FJeGLkD9PFHmLbwRwVWC3qjExIDgJKVP4vRwoQN1mzf7P5/tr+xNbBcxRYPpzzCd6kLw/arXIRo+p9r4tg3NfVv0hmb1VGd6CdDyXbMsBTy9KYI3M9RgCaHbjag4HjAKuayPB53cbnFUy95zaKFYiMzjkTsU4QxSjKMAwKPzaZEwUQpFYsbZCnhMg2OAka7T5fwCzc+G4qrPiSQKRkB+oxPHjFaRZcPnBplWwv67oqEt7IUQNAI1Xkf8T8KBH3aJD8lEe7Wnd77aRwAraQzYT3xUI9RqXIXntTPpWgGVaBL7ktTyarujkWfmzClpuLKje0AiokqI8Yg7HB+/sz7x57VeTOxJPiFI/+o0AQiocRiWfMiPDXIVyCWUE3Pj5Ww2WnBGO5f4FOWKv/j21eXusof2dzsk4i6UOdN8nYqS6oZ/N8/aLcEtmXzLZ/P+WURV+3ChBYi6sT2w5IRbKFeLhiUAH7VBJBDZ1U=
notifications:
  slack:
    secure: Pc9rBZqRk5OQggSaqQ0+u9mI/DGWtz8OSHd7DInp+fsKrxogrSScYrb6s2MlZbfM4InYtHB6CPYq1NUZ+HxmeV4zdfGP7QBXmQ1Pl7rwWvOYxzP4+jl7QW9FtjVzFpXx4OBsE9Xeec19JYNhC/7YEyUB63BJaIUJ6+EwpC2dOi+IFItL7oFnnzk07xsluKmGpLhe1713FtH+XFQaEGA2KP1lK0hM00jRyldQ8ZuAgL3yqXyzKEySuPYmDEJ6Ns3iV+Tm8BovLMkuJQoOZ8i/zBtc1pSka+m91gg16Ml/1ZWfxs0sTqrKhAWsqKiTNlpZfEo8nuW/2CrqVelOZnWTpnF07kPYoOIMYTdaKgZn0iMJeZt8rQxBh0PvdLZrHCQ49f1EPV+whyQajuUDteMuY9BMwP9DapHaIqwcTDpgNfZt7tlKHl5WSgkgNeTVWfm73/gBJHaNKXcDMszv4o2gN/IpYm9v1hlyYXq18VAc3k/HiSyJDP02i4juxyrA5O8I9fBWfwkLsnuMJ9r8IU7K3pwq+y9ol2nNwMdVW3SwEdMKhoZoL/Xbi1GL2F68tuKAlkBNI3F2dDsqhcUniiIPjisxnb/u/4CrH1pCS1pSJ+dxPp5MVxjieQwicrOj8IywbjKyn3ck4RBwNRUUX1vLujBkKLwUkxaKbfwjjHJyg6s=
