version: "3"
services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: lightapp2-apiGateway-x64
    ports:
      - "4001:4001"
  rabbitmq:
    image: rabbitmq:3
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
     RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
