version: "3"
services:
  server:
    build:
      context: .
      dockerfile: rpi.Dockerfile
    image: lightapp2-server-rpi
    ports:
      - "4001:4001"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisData:/data
  broker:
      image: eclipse-mosquitto:latest
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./mqttConfig:/mosquitto/config
        - /mosquitto/data
        - /mosquitto/log
