version: "3"
services:
  server:
    build:
      context: .
      dockerfile: rpi.Dockerfile
    image: lightapp2-server-rpi
    environment:
      - IN_DOCKER_CONTAINER=true
  redis:
    image: redis:latest
    ports:
      - "6379:6379"