version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisData:/data
  broker:
    image: eclipse-mosquitto:latest
    container_name: broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mqtt/config
      - /mqtt/data
      - /mqtt/log
