version: "3"
services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: lightapp2-apiGateway-x64
    ports:
      - "4001:4001"
  rabbit:
    image: rabbitmq:3
    hostname: "myrabbit"
    container_name: rabbit
    ports:
      - "5672:5672"
