version: "3.5"
services:
  rabbit:
    image: rabbitmq:3
    hostname: "myrabbit"
    container_name: rabbit
    ports:
      - "5672:5672"
  client:
    build:
      context: .
      cache_from:
        - rooknj/lightapp2:client-x64-latest
      dockerfile: Dockerfile
    image: lightapp2-client-x64
    ports:
      - "80:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: lightapp2-api-gateway-x64
    ports:
      - "4001:4001"
    environment:
      - RABBIT_HOST=rabbit
      - DEBUG="main,config,server,service";
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: lightapp2-controller-microservice-x64
    environment:
      - REDIS_HOST=redis # DO NOT delete this because travis needs it for some reason
      - MQTT_HOST=broker # DO NOT delete this because travis needs it for some reason
      - RABBIT_HOST=rabbit
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisData:/data
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqttConfig:/mosquitto/config
      - /mosquitto/data
      - /mosquitto/log
