language: node_js
node_js:
- stable
sudo: required
services:
- docker
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install --silent
script:
- node scripts/dockerScripts build
- yarn testIntegration
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  skip_cleanup: true
  script: node scripts/dockerScripts tag && node scripts/dockerScripts publish
  on:
    all_branches: true
env:
  global:
  - secure: njje9sb+thffhIo3evEYJM2wowYK/dt+1kCe2oACGVJ3m1bHxAoM6qi2RLlMubfP0fmelZgHSbjxLVZc/bjvnAQ0Vk5QdWHDGGxJmYnTiHDwrJMhBjDxoW7GGJDyb5Cc4UtcKJ8gAIWmVn4GmkRLj+ktNZO1Gzd1qtYLEQVwvUG/eppIRKHcicAHSqsahkmjIcvgQIGmQd1AMDfod3N7Nx1Hy5oQLQTop5vFZEGV1kBZ6WRtn3N5q6t17z1753ZNxjgS3xnqO+H9QLuMvb7YuDg8aO+f53+iK62lYUK77D5lluH2v96ZSPuvJkPEu04zz2SxW3gvaRzRyUNl0K5881chR9TLQGlJVJdRvJmngxnMeHSzaqoV2ZtXf/SULZtMrxVidzHeEuOVdfC5EO8e3XUQNeTAYQT4SwHxFK1DOIdLjjHJvnEjkqhDbreDzMxHdF9AHK9hC3t/bb0I//33RffV+t0Izf4xK3GFpLgM0bodu6r9XZkI59FlbSz20YHZgXI2F5E53TefHlo1vnIHr6iIOqBoNc+T5lQ/zw++gQ2sahIc+R3dcIleu7X6ZbbsXbyet9flSpDnWUOIFlZfbD3AJC3SbJCACjWQag9frFcj0CLZV+iIGn6aTd9kVDN/h0bXsE987khfK/IbLZ7eyv9ypM564VYLwW2fMqtmYS4=
notifications:
  slack:
    secure: cBlyybctbGPx0g4yBmaBKgr+V6Lc38Z1LOyR4ahndEGcM9wptQjDfFVSfSJxxDSS854IkI9ghCjCh1c8L/IOTyHZ7i3IeBOHuKcHG4Pf+YeeVCuAccEtDe0MOmLBty53mbULM3XM9CU5sdx5w9TEkdjvQM/H716VPEWYPdLOyV09hkB4ijcUWYCzAy2iepLz3kbtLlo9m2uNcpZ2SqKpzrDZ1wxqN/h/ohtJaMTCSK/lqCWZhQX5KBPjsFzkpuIHS6tQczF9DUVQDLIKARx4ho6M+cgJYYbua4kEy8I55sv3ZxpbgyJJdX7nBKmJNMPdFT4ciQ24hgPH6LeYt8yQzSK97OBuI0+FrPiqvutxT1mxLIaR0u97rYIUjAm0DA1UMHCiR0ngyMWxaTK5n37Um9ND46g7yJ9X1cwF2Uexk9pmT94jUvSwZEoA1qSuFnTq8+ozq40CTO862Y8kRpxI5skrrhAGRBa5L7mwSD9IXyOLWRIadYnUWA6irUTZUFNbieSeboRmc34PRPOtWgCZTDkDIqPYO1Hg0DoAPGdptIPnmYeqF3T4SLl3gr2lxQW3a+YGBJEBzLSnu8bbn4Ah/iOIbnbPk1zOSBmb/96xh3N3L9swFNtWICaZQlKvK3hJ0S/VFiP/5V8bvVPD/mgqtXXiN2Mwgcy9TVbreq+rMRo=
