version: "3"
services:
  api:
    build:
      context: .
      dockerfile: rpi.Dockerfile
    image: lightapp2-api-gateway-rpi
    ports:
      - "4001:4001"
    environment:
      - RABBIT_HOST=rabbit
  rabbit:
    image: rabbitmq:3
    hostname: "myrabbit"
    container_name: rabbit
    ports:
      - "5672:5672"

