version: "3"
services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - /mosquitto/data
      - /mosquitto/log


